// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgpnpmmkceumyfltboea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ncG5wbW1rY2V1bXlmbHRib2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4NjIzNDcsImV4cCI6MjA4MzQzODM0N30.GuS5AdPsF8WEUfurW8zHif2BaL6HjlW0VhpotM7nXtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});